export * from './icons';

export const welcomeLogo = require('./welcomeLogo.png');
export const sunLogo = require('./sunLogo.png');
export const game1Logo = require('./game1.png');
export const game2Logo = require('./game2.png');
export const game3Logo = require('./game3.png');
export const game4Logo = require('./game4.png');
export const bigCoinLogo = require('./bigCoin.png');
export const compassLogo = require('./compass.png');
export const backpack = require('./backpack.png');
export const bigMap = require('./bigMap.png');
export const bigCrown = require('./bigCrown.png');
export const closeButton = require('./closeButton.png');
export const modal = require('./modal.png');
export const trackHidden = require('./TrackHidden.png');
export const track = require('./Track.png');
export const profile = require('./Profile.png');

export const map = require('./map.png');
export const compass = require('./compass2.png');
export const hammer = require('./hammer.png');
export const picture = require('./picture.png');
export const vase = require('./vase.png');
export const egypt = require('./egypt.png');
export const bag = require('./bag.png');
export const loop = require('./loop.png');
export const crown = require('./crown.png');
export const liquid = require('./liquid.png');
export const fossil = require('./fossil.png');
export const necklace = require('./necklace.png');
export const brush = require('./brush.png');
export const plate = require('./plate.png');
export const shovel = require('./shovel.png');
export const flag = require('./flag.png');
export const x2 = require('./2X.png');
